name: Build and Deploy To Non-Prod

on: 
  workflow_dispatch:
    inputs:
      branch:
        type: string
        

jobs:
  create_infrastructure:
    name: create_infrastructure
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read 
    steps: 
    - name: Code checkout    
      uses: actions/checkout@v3
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}   
    - name: Initialise Terraform
      working-directory: ./terraform
      run: terraform init -var environment="nonprod" location="centralus" 
    - name: Apply Terraform
      working-directory: ./terraform
      run: terraform apply -var environment="nonprod" location="centralus"  github_id=${{ secrets.OATH_CLIENT_ID }} github_secret=${{ secrets.OATH_CLIENT_SECRET }} -input=false -auto-approve 
    
#   build:
#     name: build
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read 
#     steps: 
#     - name: Code checkout    
#       uses: actions/checkout@v3
#     - name: Setup Node 
#       uses: actions/setup-node@v3
#       with:
#         node-version: '18.x'
#     - name: Build    
#       run: | 
#         cd api
#         npm i
#         npm run clean
#         npm run build 
#     - name: Zip artifact for deployment
#       run: zip release.zip ./api -r
#     - name: Upload artifact for deployment job
#       uses: actions/upload-artifact@v4
#       with:
#         name: node-app
#         path: release.zip    

#   deploy-to-nonprod:
#     runs-on: ubuntu-latest
#     needs: [build,create_infrastructure]
#     environment: dev
#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v4
#         with:
#           name: node-app

#       - name: Unzip artifact for deployment
#         run: unzip release.zip
      
#       - name: 'Deploy to Azure Web App'
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: 'codepush-server-app-nonprod'
#           slot-name: 'Production'
#           package: .
#           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}


      
 

  
    

  
                
          
     
    
             
 

    
